#if ZMQ_VERSION_MINOR < 1
#define ZMQ_ROUTER_HANDOVER 0
#define ZMQ_TOS 0
#define ZMQ_IPC_FILTER_PID 0
#define ZMQ_IPC_FILTER_UID 0
#define ZMQ_IPC_FILTER_GID 0
#define ZMQ_CONNECT_RID 0
#define ZMQ_GSSAPI_SERVER 0
#define ZMQ_GSSAPI_PRINCIPAL 0
#define ZMQ_GSSAPI_SERVICE_PRINCIPAL 0
#define ZMQ_GSSAPI_PLAINTEXT 0
#define ZMQ_HANDSHAKE_IVL 0
#define ZMQ_SOCKS_PROXY 0
#define ZMQ_XPUB_NODROP 0
#endif
